apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fb6xx3qlm-go-gitops
  description: This is GitOps manifest for fb6xx3qlm-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=fb6xx3qlm-go
    backstage.io/kubernetes-id: fb6xx3qlm-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fb6xx3qlm-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fb6xx3qlm-go
