apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fb6xx3qlm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fb6xx3qlm-go 
  name: fb6xx3qlm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fb6xx3qlm-go 
